### ISSUE TITLE
package added with `packages` not available in kernel environment.

### ISSUE THREAD

**Issue by bj0** [tweag/jupyterWith#171] opened 2021-09-30 17:35 UTC
**Describe the bug**
I tried to add multiple packages to the kernel environment, but some are missing.

**To Reproduce**
I copied the getting started example and added 2 modules:
```nix
{ pkgs ? import (fetchTarball https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz) {} }:

let
    jupyter = import (builtins.fetchGit {
        url = https://github.com/tweag/jupyterWith;
    }) {};

    iPython = jupyter.kernels.iPythonWith {
        name = "ipy";
        packages = p: with p; [ numpy coconut trio ];
    };

    jupyterEnvironment = jupyter.jupyterlabWith {
        kernels = [ iPython ];
        extraPackages = p: [ p.python3Packages.jupyter_console ];
    };

in
    jupyterEnvironment.env
```

when I try go into either jupyter console or jupyter lab, I can import numpy and trio, but coconut says no module found.  There are no errors when starting with nix-shell.

**Environment**
ubuntu 20.04
nix-shell (Nix) 2.4pre20210503_6d2553a

**Comment by guaraqe** [comment] 2021-10-04 10:26
Hello, I am not well acquainted with coconut, but my impression is that it is an executable external to Python, am I correct? In this case I can understand why it doesn't show in Jupyter, since it is not a module.

**Comment by bj0** [comment] 2021-10-04 18:03
It is a module, the 'executable' is just a script that runs an interpreter from the module.  They also have a jupyter kernel in the module.  I was able to use mach-nix to get coconut and the kernel working, but I still don't understand why this didn't work.  If it couldn't find the module I would have expected an error.

Here is what I used to get the kernel working.  I mostly just use it for a jupyter console:

https://gist.github.com/bj0/aa1ed75920381144781baa669d0ed4c9

**Comment by kirelagin** [comment] 2022-02-03 20:52
I think the problem is that `python3Packages.coconut` [is defined](https://github.com/NixOS/nixpkgs/blob/07a283bb00398dc8b32e31269ca1fa051c646305/pkgs/development/python-modules/coconut/default.nix#L15) using `buildPythonApplication`, so it does not get installed as a Python module, only as a binary.

**Comment by garbas** [comment] 2022-08-17 20:27
This will be fixed and documented with next version of jupyterWith (see `main` branch)

**Closed by garbas** 2022-08-17 20:27 UTC
