### ISSUE TITLE
[Feature]: Add back the OCaml Kernel

### ISSUE THREAD

**Issue by fusetim** [tweag/jupyterWith#333] opened 2022-10-27 10:48 UTC
### What's missing?

The new version (Flake rewrite) does not feature anymore the OCaml Kernel, that I added (#162).
I would like to continue using this project with the OCaml kernel for jupyter.

### Possible solution

It should only be a rewrite of the old merged solution. I will try myself to make it work and submit a PR by the end of the week.

### Alternatives

No particular alternative.

### Additional context

Feature was previously implemented by GH-163, closing GH-162.

**Comment by djacu** [comment] 2022-10-27 11:32
Hey @fusetim 

Sorry about the OCaml kernel being removed. I tried to port what you had done into the new architecture, but I could never get it working. I created a new branch as a starting point so you don't have to start from scratch. Let me know if you get it working.

https://github.com/tweag/jupyterWith/tree/feature/add-ocaml-kernel

**Comment by djacu** [comment] 2022-10-27 11:32
I just noticed that I don't have the `postInstall` that you did. I wonder if that is the root cause of it not working.

**Comment by djacu** [comment] 2022-10-27 11:50
I'm getting the following error but I'm not sure what package to add to provide the missing binary.

```shell
[I 2022-10-27 13:48:24.159 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), new random ports
Fatal error: cannot load shared library dlllwt_unix_stubs
Reason: dlllwt_unix_stubs.so: cannot open shared object file: No such file or directory
```

**Comment by fusetim** [comment] 2022-10-27 14:25
Thank you, I will take a look at that.

**Comment by djacu** [comment] 2022-10-27 14:39
PR is up in #336.
Got some help from @thufschmitt to fix some runtime dependencies of the kernel. It is pretty hacky. If you know of a better way to fix it, feel free to suggest changes.
Fixes (re: hacks) were committed in https://github.com/tweag/jupyterWith/pull/336/commits/0346fe9f59940a874f2ed4da5259686cb98de5b0

**Closed** 2022-11-02 09:57 UTC
Labels: enhancement
